name: Java Apps - Run tests and packages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test_and_build:
    name: Test and Build samples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: run test
        run: mvn clean test | tee test.log
      - name: build artifacts
        run: mvn clean package -Dmaven.test.skip
      - name: setup artifacts
        run: mkdir artifacts && cp test.log target/*.jar artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: artifacts
